import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"no-store"};
const PLANS:Record<string,{name:string,value:number,ai:number}>={axiva:{name:"AXIVA",value:45,ai:10},axiva_plus:{name:"AXIVA Plus",value:79.8,ai:20},axiva_max:{name:"AXIVA Max",value:164.8,ai:30}};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:corsHeaders});
async function getUser(admin:any,req:Request){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))throw new Error("UNAUTHORIZED");const {data,error}=await admin.auth.getUser(h.slice(7));if(error||!data?.user)throw new Error("UNAUTHORIZED");return data.user}
async function getOrg(admin:any,userId:string){const {data,error}=await admin.from("organization_members").select("organization_id,role").eq("user_id",userId).eq("is_active",true).is("deleted_at",null).order("created_at",{ascending:true}).limit(1);if(error||!data?.[0])throw new Error("ORGANIZATION_NOT_FOUND");if(!["owner","admin"].includes(data[0].role))throw new Error("FORBIDDEN");return data[0]}
async function updateAsaas(key:string,id:string,value:number){const r=await fetch("https://api.asaas.com/v3/subscriptions/"+encodeURIComponent(id),{method:"PUT",headers:{access_token:key,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({value:Number(value.toFixed(2)),description:"AXIVA CRM - assinatura consolidada por usuários",updatePendingPayments:false})});const raw=await r.text();if(!r.ok)throw new Error("ASAAS_UPDATE_FAILED:"+raw.slice(0,220))}
async function cancelAsaas(key:string,id:string){const r=await fetch("https://api.asaas.com/v3/subscriptions/"+encodeURIComponent(id),{method:"DELETE",headers:{access_token:key,Accept:"application/json"}});if(r.status!==404&&!r.ok)throw new Error("ASAAS_CANCEL_FAILED:"+(await r.text()).slice(0,220))}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);
const key=Deno.env.get("ASAAS_API_KEY")||"",url=Deno.env.get("SUPABASE_URL")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!key||!url||!service)return json({error:"Integração de cobrança não configurada no servidor."},503);
const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
try{
const user=await getUser(admin,req),mem=await getOrg(admin,user.id),orgId=mem.organization_id;let body:any={};try{body=await req.json()}catch{}const action=String(body?.action||"");
const {data:account}=await admin.from("axiva_billing_accounts").select("id,asaas_subscription_id,status,current_amount,licensed_seats,default_plan_id").eq("organization_id",orgId).maybeSingle();if(!account)return json({error:"Conta de cobrança não encontrada."},404);
if(action==="cancel"){if(account.asaas_subscription_id)await cancelAsaas(key,account.asaas_subscription_id);await admin.from("user_plan_assignments").update({status:"suspended",updated_at:new Date().toISOString()}).eq("organization_id",orgId).eq("status","active");await admin.from("axiva_billing_accounts").update({status:"cancelled",current_amount:0,cancelled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",account.id);return json({ok:true,status:"cancelled",totalMonthly:0})}
const targetUserId=String(body?.userId||"");if(!targetUserId)return json({error:"Usuário não informado."},400);
const {data:member}=await admin.from("organization_members").select("user_id").eq("organization_id",orgId).eq("user_id",targetUserId).eq("is_active",true).is("deleted_at",null).maybeSingle();if(!member)return json({error:"Usuário não pertence à organização."},404);
const {data:assignments}=await admin.from("user_plan_assignments").select("user_id,plan_id,status,trial_ends_at").eq("organization_id",orgId);
const active=(assignments||[]).filter((x:any)=>x.status==="active"&&!x.trial_ends_at);let seats=Math.max(1,Number(account.licensed_seats||1));const defaultPlan=PLANS[account.default_plan_id]?account.default_plan_id:"axiva";let next=active.map((x:any)=>({...x}));let target=next.find((x:any)=>x.user_id===targetUserId);
if(action==="change_plan"){const planId=String(body?.planId||"");if(!PLANS[planId])return json({error:"Plano inválido."},400);if(target)target.plan_id=planId;else{if(Math.max(0,seats-next.length)===0)seats+=1;next.push({user_id:targetUserId,plan_id:planId,status:"active"})}}
else if(action==="remove_user"){if(active.length<=1)return json({error:"A última licença não pode ser removida. Para encerrar a cobrança, use Cancelar plano."},409);if(!target)return json({error:"Este usuário não possui licença ativa."},409);next=next.filter((x:any)=>x.user_id!==targetUserId);seats=Math.max(1,seats-1)}
else return json({error:"Ação inválida."},400);
const assignedTotal=next.reduce((s:number,x:any)=>s+(PLANS[x.plan_id]?.value||0),0);const unassigned=Math.max(0,seats-next.length);const total=Number((assignedTotal+unassigned*(PLANS[defaultPlan]?.value||45)).toFixed(2));if(!account.asaas_subscription_id)return json({error:"A assinatura Asaas não está ativa para alteração."},409);
try{await updateAsaas(key,account.asaas_subscription_id,total)}catch{return json({error:"O Asaas não permitiu alterar o valor da assinatura atual.",requiresReauthorization:true,details:"A forma de pagamento pode exigir nova autorização no Asaas."},409)}
if(action==="change_plan"){const planId=String(body.planId);await admin.from("user_plan_assignments").upsert({organization_id:orgId,user_id:targetUserId,plan_id:planId,status:"active",trial_started_at:null,trial_ends_at:null,assigned_by:user.id,assigned_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"organization_id,user_id"});await admin.from("ai_user_settings").upsert({organization_id:orgId,user_id:targetUserId,daily_message_limit:PLANS[planId].ai,updated_at:new Date().toISOString()},{onConflict:"organization_id,user_id"})}else await admin.from("user_plan_assignments").update({status:"suspended",updated_at:new Date().toISOString()}).eq("organization_id",orgId).eq("user_id",targetUserId);
await admin.from("axiva_billing_accounts").update({status:"active",current_amount:total,licensed_seats:seats,updated_at:new Date().toISOString()}).eq("id",account.id);return json({ok:true,totalMonthly:total,licensedSeats:seats,action})
}catch(e){const code=String(e?.message||e);if(code==="UNAUTHORIZED")return json({error:"Sessão inválida."},401);if(code==="FORBIDDEN")return json({error:"Somente o proprietário ou administrador da empresa pode alterar planos."},403);if(code==="ORGANIZATION_NOT_FOUND")return json({error:"Organização não encontrada."},404);return json({error:"Não foi possível concluir a operação de cobrança.",details:code.slice(0,220)},500)}});